# -*- coding: utf-8 -*-
"""Ingredient 01

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1H9gPywX35H3pjPHUrNPXnVTuWjxCptt2
"""

import streamlit as st

# ------------------ DATA ------------------ #
recipe_name = "Salmon with fresh salad"
cooking_time = "15-20 mins"
calories = 325

ingredients = {
    "Avocado": (1, True),
    "Eggs": (2, True),
    "Rice": ("50g", False),
    "Lettuce": ("50g", False),
    "Lightly salted salmon": ("100g", True),
    "Microgreens": ("10g", False),
    "Tomatoes": (1, True),
}

# ------------------ UI ------------------ #
st.title(recipe_name)
st.image("https://images.unsplash.com/photo-1551218808-94e220e084d2", caption="Fresh Salmon Bowl", use_column_width=True)

col1, col2 = st.columns(2)
col1.metric("⏱️ Time", cooking_time)
col2.metric("🔥 Calories", f"{calories} cal")

# Tab for Ingredients & How to cook
tab1, tab2 = st.tabs(["🧂 Ingredients", "👨‍🍳 How to Cook"])

# ------------------ INGREDIENTS TAB ------------------ #
with tab1:
    st.subheader("Ingredients")
    for item, (amount, available) in ingredients.items():
        status = "✅" if available else "🛒"
        st.write(f"- {item}: {amount} {status}")

# ------------------ HOW TO COOK TAB ------------------ #
with tab2:
    st.subheader("Step 1")
    st.write("Preheat oven to 400°F. Line a small rimmed baking sheet with foil. Place salmon on the prepared pan. Drizzle with oil; season with salt. Bake until the salmon flakes easily with a fork, 8 to 10 minutes.")

    st.subheader("Step 2")
    st.write("Meanwhile, combine rice and water in a small saucepan; cook according to package directions. Mix mayonnaise and Sriracha in a small bowl; set aside. Whisk tamari, mirin, ginger, crushed red pepper and salt in another small bowl; set aside.")

    st.subheader("Step 3")
    st.write("Divide the rice between 2 bowls. Top with salmon, avocado, cucumber and kimchi. Drizzle with the tamari mixture and the mayonnaise mixture. Mix the bowls, if desired, and serve with nori.")

st.success("Enjoy your meal 😋")